[functions.create-pix]
verify_jwt = false

[functions.mercado-pago-webhook]
verify_jwt = false

[auth.email.template.confirmation]
subject = "Confirme seu acesso à PS Estética"
content_path = "./supabase/templates/confirmation.html"

[auth.email.template.invite]
subject = "Você foi convidado para a PS Estética"
content_path = "./supabase/templates/invite.html"

[auth.email.template.recovery]
subject = "Redefina sua senha da PS Estética"
content_path = "./supabase/templates/recovery.html"

[auth.email.template.magic_link]
subject = "Seu acesso seguro à PS Estética"
content_path = "./supabase/templates/magic-link.html"

[auth.email.template.email_change]
subject = "Confirme seu novo e-mail"
content_path = "./supabase/templates/email-change.html"

[auth.email.template.reauthentication]
subject = "Seu código de segurança da PS Estética"
content_path = "./supabase/templates/reauthentication.html"
