"use client";

import { FormEvent, useEffect, useMemo, useRef, useState } from "react";
import Image from "next/image";
import { trackMetaCustomEvent, trackMetaEvent } from "../../lib/meta-pixel";
import { supabase } from "../../lib/supabase";
import { formatBrazilianWhatsapp, INVALID_WHATSAPP_MESSAGE, isValidBrazilianWhatsapp, whatsappDigits } from "../../lib/whatsapp";
import s from "../lavieen/lavieen.module.css";

type Step = 0 | 1 | 2 | 3 | 4 | 5 | 6;
type Key = "motivation" | "intent";
type Answers = Record<Key, string>;
type Slot = { slot_id: number; service_name: string; starts_at: string; ends_at: string };
type Lead = { lead_id: number; reservation_token: string };
type Booking = { booking_id: number; booking_token: string; service_name: string; starts_at: string; ends_at: string; deposit_cents: number; payment_expires_at: string };
type Pix = { pix_copy_paste?: string; qr_code_base64?: string; ticket_url?: string };

const questions: Array<{ key: Key; title: string; help: string; options: string[] }> = [
  { key: "motivation", title: "O que mais motiva você a buscar depilação a laser?", help: "Escolha a opção que mais combina com o seu momento.", options: [
    "Cansei de depender de lâmina ou cera", "Pelos encravados me incomodam", "Quero mais praticidade no dia a dia",
    "Quero reduzir os pelos dessas regiões", "É um pouco de tudo",
  ] },
  { key: "intent", title: "Quando você gostaria de começar?", help: "Essa resposta ajuda a equipe a entender melhor o seu momento.", options: [
    "Quero aproveitar o próximo Laser Day", "Quero começar nas próximas semanas",
    "Estou comparando valores primeiro", "Ainda não tenho certeza",
  ] },
];

const availableRegions = ["Axilas", "Virilha", "Buço", "Rosto", "Meia perna", "Pernas", "Braços", "Costas", "Abdômen", "Outra região"];
const regionTone = ["amber", "terracotta", "peach", "lilac", "taupe"];

const formatSlot = (value: string) => new Intl.DateTimeFormat("pt-BR", { timeZone: "America/Sao_Paulo", weekday: "long", day: "2-digit", month: "long", hour: "2-digit", minute: "2-digit" }).format(new Date(value));
const cookie = (name: string) => document.cookie.split(";").map((item) => item.trim()).find((item) => item.startsWith(`${name}=`))?.slice(name.length + 1) ?? null;

export default function LaserDayPage() {
  const [step, setStep] = useState<Step>(0);
  const [answers, setAnswers] = useState<Answers>({ motivation: "", intent: "" });
  const [selectedRegions, setSelectedRegions] = useState<string[]>([]);
  const [name, setName] = useState(""); const [phone, setPhone] = useState(""); const [email, setEmail] = useState("");
  const [lead, setLead] = useState<Lead | null>(null); const [slots, setSlots] = useState<Slot[]>([]); const [selected, setSelected] = useState<Slot | null>(null);
  const [booking, setBooking] = useState<Booking | null>(null); const [pix, setPix] = useState<Pix | null>(null); const [paid, setPaid] = useState(false);
  const [loading, setLoading] = useState(false); const [notice, setNotice] = useState("");
  const viewTracked = useRef(false); const startTracked = useRef(false); const leadTracked = useRef<number | null>(null); const purchaseTracked = useRef<number | null>(null);
  const current = step >= 2 && step <= 3 ? questions[step - 2] : null;
  const progress = step === 0 ? 0 : step <= 3 ? Math.round(step * (75 / 3)) : step === 4 ? 90 : 100;
  const regionsLabel = selectedRegions.length ? selectedRegions.join(", ") : "as regiões escolhidas";
  const whatsapp = useMemo(() => {
    const message = booking
      ? `Oi! Sou ${name}. Fiz o quiz do Laser Day 😊\nTenho interesse em ${regionsLabel} e pré-reservei ${formatSlot(booking.starts_at)}. Quero confirmar os detalhes.`
      : `Oi! Fiz o quiz do Laser Day 😊\nTenho interesse em ${regionsLabel} e ${answers.intent ? answers.intent.toLowerCase() : "quero conhecer a próxima edição"}. Gostaria de consultar a condição e os horários.`;
    return `https://wa.me/5511934580476?text=${encodeURIComponent(message)}`;
  }, [answers.intent, booking, name, regionsLabel]);

  useEffect(() => { if (!viewTracked.current) { viewTracked.current = true; trackMetaEvent("ViewContent", { content_name: "Quiz Laser Day", content_category: "laser", content_ids: ["laser"], content_type: "product" }); } }, []);
  function start() { if (!startTracked.current) { startTracked.current = true; trackMetaCustomEvent("QuizStart", { content_name: "Quiz Laser Day", content_category: "laser", content_ids: ["laser"], content_type: "product" }); } setStep(1); setTimeout(() => document.getElementById("quiz-laser")?.scrollIntoView({ behavior: "smooth", block: "start" }), 40); }
  function choose(value: string) { if (!current) return; setAnswers((old) => ({ ...old, [current.key]: value })); setLead(null); setTimeout(() => setStep((step + 1) as Step), 140); }
  function toggleRegion(region: string) { setSelectedRegions((current) => current.includes(region) ? current.filter((item) => item !== region) : [...current, region]); setLead(null); }
  function source() { const p = new URLSearchParams(location.search); return { landing_page: "laserday", quiz_answers: { ...answers, selected_regions: selectedRegions }, utm_source: p.get("utm_source"), utm_medium: p.get("utm_medium"), utm_campaign: p.get("utm_campaign"), utm_content: p.get("utm_content"), utm_term: p.get("utm_term"), referrer: document.referrer || null, fbp: cookie("_fbp"), fbc: cookie("_fbc") }; }
  async function saveLead() {
    if (lead) return lead;
    const highIntent = answers.intent === "Quero aproveitar o próximo Laser Day" || answers.intent === "Quero começar nas próximas semanas";
    const { data, error } = await supabase.rpc("capture_lead_session", { p_name: name.trim(), p_phone: whatsappDigits(phone), p_service_slug: "laser", p_experience: "primeira", p_timing: highIntent ? "semana" : "pesquisando", p_source: source(), p_email: email.trim().toLowerCase() });
    const row = data?.[0] as Lead | undefined; if (error || !row) return null;
    const next = { lead_id: Number(row.lead_id), reservation_token: row.reservation_token }; setLead(next);
    if (leadTracked.current !== next.lead_id) { leadTracked.current = next.lead_id; trackMetaEvent("Lead", { content_name: "Quiz Laser Day", content_category: "laser" }); }
    return next;
  }
  async function loadSlots() { const { data, error } = await supabase.rpc("list_open_slots", { p_service_slug: "laser" }); if (error) { setSlots([]); setNotice("Não foi possível consultar a agenda agora."); } else setSlots(((data ?? []) as Slot[]).slice(0, 8)); }
  async function submitContact(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (loading) return; if (!isValidBrazilianWhatsapp(phone)) return setNotice(INVALID_WHATSAPP_MESSAGE); setLoading(true); setNotice(""); if (!await saveLead()) { setNotice("Não conseguimos registrar seus dados agora. Confira e tente novamente."); setLoading(false); return; } setStep(5); await loadSlots(); setLoading(false); }
  async function reserve(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (!selected || loading) return; setLoading(true); setNotice(""); const session = await saveLead();
    if (!session) { setNotice("Não foi possível validar seus dados."); setLoading(false); return; }
    const { data, error } = await supabase.rpc("reserve_slot_secure", { p_lead_id: session.lead_id, p_reservation_token: session.reservation_token, p_slot_id: selected.slot_id });
    if (error || !data?.[0]) { setNotice("Este horário ficou indisponível. Escolha outra opção."); await loadSlots(); setSelected(null); setLoading(false); return; }
    const next = data[0] as Booking; setBooking(next); setStep(6); trackMetaEvent("Schedule", { content_name: next.service_name, content_ids: ["laser"], content_type: "product", currency: "BRL", value: next.deposit_cents / 100 }, `booking-${next.booking_id}-schedule`);
    const { data: pixData, error: pixError } = await supabase.functions.invoke("create-pix", { body: { bookingToken: next.booking_token } });
    if (pixError || !pixData?.payment) setNotice(pixData?.error ?? "Sua vaga foi separada, mas não foi possível gerar o Pix agora."); else { setPix(pixData.payment as Pix); trackMetaEvent("InitiateCheckout", { content_name: next.service_name, content_ids: ["laser"], content_type: "product", currency: "BRL", value: next.deposit_cents / 100 }); } setLoading(false);
  }
  useEffect(() => { if (!booking?.booking_token || paid) return; const timer = setInterval(async () => { const { data } = await supabase.rpc("get_booking_public_status", { p_booking_token: booking.booking_token }); if (data?.[0]?.booking_status === "confirmed") { setPaid(true); if (purchaseTracked.current !== booking.booking_id) { purchaseTracked.current = booking.booking_id; trackMetaEvent("Purchase", { content_name: booking.service_name, content_ids: ["laser"], content_type: "product", currency: "BRL", value: booking.deposit_cents / 100 }, `booking-${booking.booking_id}-purchase`); } clearInterval(timer); } if (data?.[0]?.booking_status === "expired") { setNotice("O prazo do Pix terminou e o horário foi liberado."); clearInterval(timer); } }, 5000); return () => clearInterval(timer); }, [booking, paid]);
  async function copyPix() { if (pix?.pix_copy_paste) { await navigator.clipboard.writeText(pix.pix_copy_paste); setNotice("Código Pix copiado."); } }

  return <main className={s.page}>
    <header className={s.header}><a href="#inicio"><Image src="/ps-estetica-logo-oficial.png" width={246} height={80} alt="PS Estética Avançada" priority /></a><a className={s.headerCta} href={whatsapp} target="_blank" rel="noreferrer">Falar com a equipe</a></header>
    <section className={s.hero} id="inicio"><div className={s.heroCopy}><p className={s.eyebrow}>Laser Day • PS Estética</p><h1>Menos dependência de lâmina e cera. <em>Mais praticidade para você.</em></h1><p className={s.heroText}>Se pelos encravados ou a necessidade de se depilar toda hora já cansaram você, escolha as regiões que mais incomodam e veja a condição do próximo Laser Day da PS Estética.</p><button className={s.primary} onClick={start}>Quero ver a condição <span>›</span></button><p className={s.heroTrust}><b>Leva menos de 1 minuto</b><span>São Bernardo do Campo • ABC Paulista</span></p></div><div className={s.heroPanel}><span className={s.orbit} /><p>Depilação a laser</p><strong>3 perguntas</strong><ul><li>Escolha uma ou mais regiões</li><li>Conte o que mais incomoda</li><li>Informe quando quer começar</li></ul><small>No final, consulte a condição e fale com a equipe sobre os horários.</small></div></section>
    <section className={s.quizSection} id="quiz-laser"><div className={s.quizIntro}><p className={s.eyebrow}>Depilação a laser</p><h2>São apenas três perguntas rápidas.</h2><p>No final, você poderá consultar a condição da próxima edição e falar com a equipe sobre os horários disponíveis.</p></div><div className={s.quizCard} aria-live="polite"><div className={s.quizTop}><span>{step === 0 ? "Pronto para começar" : step <= 3 ? `Pergunta ${step} de 3` : step === 4 ? "Seus dados" : step === 5 ? "Sua condição" : "Pré-reserva"}</span><b>{progress}%</b></div><div className={s.progress}><span style={{ width: `${progress}%` }} /></div>
      {step === 0 && <div className={s.quizBody}><p className={s.quizKicker}>Depilação a laser</p><h3>São apenas 3 perguntas rápidas.</h3><p className={s.quizText}>No final, você poderá consultar a condição da próxima edição e falar com a equipe sobre os horários disponíveis.</p><button className={s.primary} onClick={start}>Começar <span>›</span></button><p className={s.cardTrust}><b>Leva menos de 1 minuto</b><br /><span>Você pode escolher mais de uma região.</span></p></div>}
      {step === 1 && <div className={s.quizBody}><p className={s.quizKicker}>Pergunta 1 de 3</p><h3>Quais regiões você gostaria de tratar?</h3><p className={s.quizText}>Escolha todas as regiões que realmente interessam a você.</p><div className={s.options}>{availableRegions.map((region,index) => <button type="button" key={region} className={`${s.regionOption} ${selectedRegions.includes(region) ? s.selected : ""}`} data-tone={regionTone[index % regionTone.length]} onClick={() => toggleRegion(region)}><span className={s.regionBadge} aria-hidden="true">{selectedRegions.includes(region) ? "✓" : region.slice(0,2)}</span><span><b>{region}</b></span><i>{selectedRegions.includes(region) ? "✓" : "+"}</i></button>)}</div><button type="button" className={s.primary} disabled={selectedRegions.length === 0} onClick={() => setStep(2)}>Continuar <span>›</span></button></div>}
      {current && <div className={s.quizBody}><p className={s.quizKicker}>Pergunta {step} de 3</p><h3>{current.title}</h3><p className={s.quizText}>{current.help}</p><div className={s.options}>{current.options.map((option) => <button key={option} className={answers[current.key] === option ? s.selected : ""} onClick={() => choose(option)}><span><b>{option}</b></span><i>›</i></button>)}</div><button className={s.back} onClick={() => setStep((step - 1) as Step)}>Voltar</button></div>}
      {step === 4 && <form className={`${s.quizBody} ${s.contactForm}`} onSubmit={submitContact}><p className={s.quizKicker}>Sua condição está quase pronta</p><h3>Deixe seus dados para continuar.</h3><p className={s.quizText}>Você selecionou <b>{regionsLabel}</b>. A equipe receberá também o que mais incomoda e quando você pretende começar.</p><label>Nome<input required minLength={2} value={name} onChange={(e) => { setName(e.target.value); setLead(null); }} autoComplete="name" /></label><label>WhatsApp<input required value={phone} onChange={(e) => { setPhone(formatBrazilianWhatsapp(e.target.value)); setLead(null); setNotice(""); }} inputMode="numeric" maxLength={15} minLength={15} pattern="\([1-9]\d\) 9\d{4}-\d{4}" title={INVALID_WHATSAPP_MESSAGE} placeholder="(11) 90000-0000" /><small>Informe um celular com DDD e todos os 9 dígitos.</small></label><label>E-mail<input required type="email" value={email} onChange={(e) => { setEmail(e.target.value); setLead(null); }} autoComplete="email" /></label><button className={s.primary} disabled={loading}>{loading ? "Consultando…" : "Ver minha condição"} <span>›</span></button>{notice && <p className={s.notice}>{notice}</p>}<button className={s.back} type="button" onClick={() => setStep(3)}>Voltar</button><small className={s.privacy}>Seus dados serão usados apenas no atendimento da PS Estética.</small></form>}
      {step === 5 && <div className={s.quizBody}><p className={s.resultLabel}>Pronto! Recebemos suas respostas.</p><h3>{regionsLabel}.</h3><p className={s.resultText}>Agora veja a condição da próxima edição do <b>Laser Day da PS Estética</b> para depilação a laser.</p><div className={s.answerSummary}><span>Regiões escolhidas</span><strong>{regionsLabel}</strong></div><div className={s.scheduleHead}><p className={s.quizKicker}>Próxima edição • São Bernardo do Campo/SP</p><h4>Consulte a condição e os horários disponíveis</h4></div>{loading && <p className={s.notice}>Consultando a agenda…</p>}{!loading && slots.length > 0 && <div className={s.slots}>{slots.map((slot) => <button key={slot.slot_id} onClick={() => setSelected(slot)} className={selected?.slot_id === slot.slot_id ? s.selectedSlot : ""}><span><small>Disponível</small>{formatSlot(slot.starts_at)}</span><i>›</i></button>)}</div>}{!loading && slots.length === 0 && <div className={s.empty}><b>Consulte a próxima edição com a equipe.</b><p>A recepção informa o valor para suas regiões, possíveis combinações e a disponibilidade real da agenda.</p><a href={whatsapp} target="_blank" rel="noreferrer">Ver condição Laser Day</a></div>}{selected && <form className={s.reserveBox} onSubmit={reserve}><div><small>Horário escolhido</small><b>{formatSlot(selected.starts_at)}</b></div><p className={s.reserveEmail}>A confirmação será enviada para <b>{email}</b></p><button className={s.primary} disabled={loading}>{loading ? "Criando pré-reserva…" : "Quero consultar um horário"} <span>›</span></button></form>}<small className={s.privacy}>A condição está sujeita às áreas participantes e à disponibilidade real da agenda.</small>{notice && <p className={s.notice}>{notice}</p>}</div>}
      {step === 6 && booking && <div className={s.quizBody}><p className={s.resultLabel}>Horário separado para você</p><h3>{formatSlot(booking.starts_at)}</h3>{paid ? <div className={s.paid}><b>Pagamento confirmado</b><p>Seu horário está confirmado.</p><a href={whatsapp} target="_blank" rel="noreferrer">Falar com a equipe</a></div> : <><p className={s.resultText}>Conclua o sinal de R$ {(booking.deposit_cents / 100).toFixed(2).replace(".", ",")} para confirmar. Se o prazo expirar, o horário volta a ficar disponível.</p>{pix?.qr_code_base64 && <Image className={s.qr} src={`data:image/png;base64,${pix.qr_code_base64}`} width={220} height={220} alt="QR Code Pix" />}{pix?.pix_copy_paste && <button className={s.primary} type="button" onClick={copyPix}>Copiar código Pix</button>}{pix?.ticket_url && <a className={s.paymentLink} href={pix.ticket_url} target="_blank" rel="noreferrer">Abrir pagamento</a>}</>}{notice && <p className={s.notice}>{notice}</p>}</div>}
    </div></section>
    <section className={s.benefits}><div className={s.sectionIntro}><p className={s.eyebrow}>Condição especial • próxima edição</p><h2>Uma data dedicada à depilação a laser.</h2><p>No Laser Day, a PS Estética reserva uma data específica para atendimentos nas áreas participantes. A equipe informa a condição das regiões selecionadas, combinações possíveis e horários disponíveis.</p></div><a className={s.primary} href={whatsapp} target="_blank" rel="noreferrer">Quero consultar um horário <span>›</span></a><p className={s.disclaimer}>Atendimento em São Bernardo do Campo/SP. Você será direcionada para o WhatsApp da PS Estética.</p></section>
    <section className={s.how}><div className={s.sectionIntro}><p className={s.eyebrow}>Para quem cansou de organizar a rotina em torno dos pelos</p><h2>Redução progressiva com foco nas regiões que realmente incomodam.</h2></div><ol><li><span>1</span><div><h3>Menos métodos temporários</h3><p>Uma alternativa para diminuir a necessidade constante de recorrer à lâmina ou à cera.</p></div></li><li><span>2</span><div><h3>Comece pelo que importa</h3><p>Você não precisa fechar áreas que não interessam. Escolha as regiões que fazem diferença na sua rotina.</p></div></li><li><span>3</span><div><h3>Protocolo individual</h3><p>Características individuais influenciam o protocolo e a quantidade de sessões necessárias.</p></div></li></ol></section>
    <section className={s.fit}><div><p className={s.eyebrow}>Próximo Laser Day</p><h2>Converse com a equipe antes de decidir.</h2><p>A recepção recebe suas regiões e seu momento, evitando que você precise recomeçar a conversa.</p><a className={s.primary} href={whatsapp} target="_blank" rel="noreferrer">Quero falar com a equipe <span>›</span></a></div><div className={s.fitCards}><article><span>01</span><h3>Nunca fiz depilação a laser. Posso participar?</h3><p>Sim. A equipe explica como funciona e orienta você antes da realização.</p></article><article><span>02</span><h3>Posso fazer mais de uma região?</h3><p>Sim, desde que estejam entre as áreas participantes da edição. A equipe informa as combinações disponíveis.</p></article><article><span>03</span><h3>Quantas sessões vou precisar?</h3><p>Isso varia conforme a região e características individuais. O quiz não define a quantidade adequada.</p></article><article><span>04</span><h3>Preciso reservar sem falar com ninguém?</h3><p>Não. No WhatsApp, você pode esclarecer suas dúvidas antes de decidir.</p></article><article><span>05</span><h3>Onde acontece?</h3><p>Na PS Estética, em São Bernardo do Campo/SP.</p></article></div></section>
    <section className={s.confidence}><p className={s.eyebrow}>Laser Day • PS Estética</p><h2>Já sabe quais regiões gostaria de tratar?</h2><p>Consulte a condição da próxima edição do Laser Day e veja os horários disponíveis.</p><div><span>Depilação a laser</span><span>São Bernardo do Campo • ABC Paulista</span><span>Condição sujeita à agenda</span></div><a className={s.primary} href={whatsapp} target="_blank" rel="noreferrer">Quero consultar disponibilidade <span>›</span></a></section>
    <footer className={s.footer}><Image src="/ps-estetica-logo-oficial.png" width={246} height={80} alt="PS Estética" /><p>São Bernardo do Campo • ABC Paulista</p><small>Depilação a laser promove redução progressiva dos pelos. Resposta ao tratamento, protocolo e número de sessões podem variar conforme características individuais.</small></footer>
  </main>;
}
