"use client";

import { FormEvent, useEffect, useMemo, useRef, useState } from "react";
import Image from "next/image";
import { trackMetaCustomEvent, trackMetaEvent } from "../../lib/meta-pixel";
import { supabase } from "../../lib/supabase";
import { formatBrazilianWhatsapp, INVALID_WHATSAPP_MESSAGE, isValidBrazilianWhatsapp, whatsappDigits } from "../../lib/whatsapp";
import s from "../lavieen/lavieen.module.css";

type Step = 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7;
type Key = "concern" | "impact" | "priority" | "intent";
type Answers = Record<Key, string>;
type Slot = { slot_id: number; service_name: string; starts_at: string; ends_at: string };
type Lead = { lead_id: number; reservation_token: string };
type Booking = { booking_id: number; booking_token: string; service_name: string; starts_at: string; ends_at: string; deposit_cents: number; payment_expires_at: string };
type Pix = { pix_copy_paste?: string; qr_code_base64?: string; ticket_url?: string };

const questions: Array<{ key: Key; title: string; help?: string; options: Array<{ label: string; detail?: string }> }> = [
  { key: "concern", title: "Qual região você mais gostaria de tratar com depilação a laser?", options: [
    { label: "Axilas" }, { label: "Virilha" }, { label: "Pernas" }, { label: "Buço/Rosto" },
    { label: "Outra região" }, { label: "Quero tratar mais de uma região" },
  ] },
  { key: "impact", title: "Além dessa, tem outra região em que os pelos também incomodam?", options: [
    { label: "Sim, quero tratar mais de uma área" }, { label: "Talvez, dependendo da condição" },
    { label: "Não, quero focar apenas nessa região" },
  ] },
  { key: "priority", title: "O que mais incomoda você nessas regiões?", options: [
    { label: "Ter que depilar com frequência" }, { label: "Pelos encravados" },
    { label: "Irritação depois da depilação" }, { label: "A aparência dos pelos" }, { label: "Um pouco de tudo" },
  ] },
  { key: "intent", title: "Se houver uma condição especial para as regiões que você escolheu, você gostaria de aproveitar o próximo Laser Day?", options: [
    { label: "Sim, quero ver a condição" }, { label: "Sim, quero consultar os horários" }, { label: "Quero saber o valor primeiro" },
  ] },
];

const availableRegions = ["Axilas", "Virilha", "Pernas", "Buço/Rosto", "Meia perna", "Braços", "Costas", "Abdômen", "Outra região"];
const regionTone: Record<string, string> = { Axilas: "amber", Virilha: "terracotta", Pernas: "taupe", "Buço/Rosto": "lilac", "Outra região": "peach", "Quero tratar mais de uma região": "amber" };

const formatSlot = (value: string) => new Intl.DateTimeFormat("pt-BR", { timeZone: "America/Sao_Paulo", weekday: "long", day: "2-digit", month: "long", hour: "2-digit", minute: "2-digit" }).format(new Date(value));
const cookie = (name: string) => document.cookie.split(";").map((item) => item.trim()).find((item) => item.startsWith(`${name}=`))?.slice(name.length + 1) ?? null;

export default function LaserDayPage() {
  const [step, setStep] = useState<Step>(0);
  const [answers, setAnswers] = useState<Answers>({ concern: "", impact: "", priority: "", intent: "" });
  const [otherRegions, setOtherRegions] = useState<string[]>([]);
  const [name, setName] = useState(""); const [phone, setPhone] = useState(""); const [email, setEmail] = useState("");
  const [lead, setLead] = useState<Lead | null>(null); const [slots, setSlots] = useState<Slot[]>([]); const [selected, setSelected] = useState<Slot | null>(null);
  const [booking, setBooking] = useState<Booking | null>(null); const [pix, setPix] = useState<Pix | null>(null); const [paid, setPaid] = useState(false);
  const [loading, setLoading] = useState(false); const [notice, setNotice] = useState("");
  const viewTracked = useRef(false); const startTracked = useRef(false); const leadTracked = useRef<number | null>(null); const purchaseTracked = useRef<number | null>(null);
  const current = step >= 1 && step <= 4 ? questions[step - 1] : null;
  const progress = step === 0 ? 0 : step <= 4 ? step * 20 : step === 5 ? 90 : 100;
  const selectedRegions = useMemo(() => {
    const primary = answers.concern && answers.concern !== "Quero tratar mais de uma região" ? [answers.concern] : [];
    return [...new Set([...primary, ...otherRegions])];
  }, [answers.concern, otherRegions]);
  const regionsLabel = selectedRegions.length ? selectedRegions.join(", ") : "as regiões escolhidas";
  const whatsapp = useMemo(() => `https://wa.me/5511934580476?text=${encodeURIComponent(booking ? `Olá! Sou ${name}. Fiz o quiz de depilação a laser e pré-reservei ${formatSlot(booking.starts_at)}.` : `Olá! Sou ${name || "cliente"}. Fiz o quiz Laser Day e quero consultar a condição para: ${regionsLabel}.`)}`, [booking, name, regionsLabel]);

  useEffect(() => { if (!viewTracked.current) { viewTracked.current = true; trackMetaEvent("ViewContent", { content_name: "Quiz Laser Day", content_category: "laser", content_ids: ["laser"], content_type: "product" }); } }, []);
  function start() { if (!startTracked.current) { startTracked.current = true; trackMetaCustomEvent("QuizStart", { content_name: "Quiz Laser Day", content_category: "laser", content_ids: ["laser"], content_type: "product" }); } setStep(1); setTimeout(() => document.getElementById("quiz-laser")?.scrollIntoView({ behavior: "smooth", block: "start" }), 40); }
  function choose(value: string) { if (!current) return; setAnswers((old) => ({ ...old, [current.key]: value })); setLead(null); if (current.key === "impact" && value !== "Não, quero focar apenas nessa região") return; setTimeout(() => setStep((step + 1) as Step), 140); }
  function toggleRegion(region: string) { setOtherRegions((current) => current.includes(region) ? current.filter((item) => item !== region) : [...current, region]); setLead(null); }
  function source() { const p = new URLSearchParams(location.search); return { landing_page: "laserday", quiz_answers: { ...answers, selected_regions: selectedRegions }, utm_source: p.get("utm_source"), utm_medium: p.get("utm_medium"), utm_campaign: p.get("utm_campaign"), utm_content: p.get("utm_content"), utm_term: p.get("utm_term"), referrer: document.referrer || null, fbp: cookie("_fbp"), fbc: cookie("_fbc") }; }
  async function saveLead() {
    if (lead) return lead;
    const { data, error } = await supabase.rpc("capture_lead_session", { p_name: name.trim(), p_phone: whatsappDigits(phone), p_service_slug: "laser", p_experience: "primeira", p_timing: answers.intent.includes("disponibilidade") ? "semana" : "pesquisando", p_source: source(), p_email: email.trim().toLowerCase() });
    const row = data?.[0] as Lead | undefined; if (error || !row) return null;
    const next = { lead_id: Number(row.lead_id), reservation_token: row.reservation_token }; setLead(next);
    if (leadTracked.current !== next.lead_id) { leadTracked.current = next.lead_id; trackMetaEvent("Lead", { content_name: "Quiz Laser Day", content_category: "laser" }); }
    return next;
  }
  async function loadSlots() { const { data, error } = await supabase.rpc("list_open_slots", { p_service_slug: "laser" }); if (error) { setSlots([]); setNotice("Não foi possível consultar a agenda agora."); } else setSlots(((data ?? []) as Slot[]).slice(0, 8)); }
  async function submitContact(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (loading) return; if (!isValidBrazilianWhatsapp(phone)) return setNotice(INVALID_WHATSAPP_MESSAGE); setLoading(true); setNotice(""); if (!await saveLead()) { setNotice("Não conseguimos registrar seus dados agora. Confira e tente novamente."); setLoading(false); return; } setStep(6); await loadSlots(); setLoading(false); }
  async function reserve(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (!selected || loading) return; setLoading(true); setNotice(""); const session = await saveLead();
    if (!session) { setNotice("Não foi possível validar seus dados."); setLoading(false); return; }
    const { data, error } = await supabase.rpc("reserve_slot_secure", { p_lead_id: session.lead_id, p_reservation_token: session.reservation_token, p_slot_id: selected.slot_id });
    if (error || !data?.[0]) { setNotice("Este horário ficou indisponível. Escolha outra opção."); await loadSlots(); setSelected(null); setLoading(false); return; }
    const next = data[0] as Booking; setBooking(next); setStep(7); trackMetaEvent("Schedule", { content_name: next.service_name, content_ids: ["laser"], content_type: "product", currency: "BRL", value: next.deposit_cents / 100 }, `booking-${next.booking_id}-schedule`);
    const { data: pixData, error: pixError } = await supabase.functions.invoke("create-pix", { body: { bookingToken: next.booking_token } });
    if (pixError || !pixData?.payment) setNotice(pixData?.error ?? "Sua vaga foi separada, mas não foi possível gerar o Pix agora."); else { setPix(pixData.payment as Pix); trackMetaEvent("InitiateCheckout", { content_name: next.service_name, content_ids: ["laser"], content_type: "product", currency: "BRL", value: next.deposit_cents / 100 }); } setLoading(false);
  }
  useEffect(() => { if (!booking?.booking_token || paid) return; const timer = setInterval(async () => { const { data } = await supabase.rpc("get_booking_public_status", { p_booking_token: booking.booking_token }); if (data?.[0]?.booking_status === "confirmed") { setPaid(true); if (purchaseTracked.current !== booking.booking_id) { purchaseTracked.current = booking.booking_id; trackMetaEvent("Purchase", { content_name: booking.service_name, content_ids: ["laser"], content_type: "product", currency: "BRL", value: booking.deposit_cents / 100 }, `booking-${booking.booking_id}-purchase`); } clearInterval(timer); } if (data?.[0]?.booking_status === "expired") { setNotice("O prazo do Pix terminou e o horário foi liberado."); clearInterval(timer); } }, 5000); return () => clearInterval(timer); }, [booking, paid]);
  async function copyPix() { if (pix?.pix_copy_paste) { await navigator.clipboard.writeText(pix.pix_copy_paste); setNotice("Código Pix copiado."); } }

  return <main className={s.page}>
    <header className={s.header}><a href="#inicio"><Image src="/ps-estetica-logo-oficial.png" width={246} height={80} alt="PS Estética Avançada" priority /></a><a className={s.headerCta} href={whatsapp} target="_blank" rel="noreferrer">Falar com a equipe</a></header>
    <section className={s.hero} id="inicio"><div className={s.heroCopy}><p className={s.eyebrow}>Laser Day • PS Estética</p><h1>Em quais regiões os pelos <em>mais incomodam você?</em></h1><p className={s.heroText}>Responda algumas perguntas rápidas e descubra a <b>condição especial do próximo Laser Day da PS Estética</b> para as áreas que você gostaria de tratar.</p><button className={s.primary} onClick={start}>Começar <span>›</span></button><p className={s.heroTrust}><b>Leva menos de 1 minuto</b><span>São Bernardo do Campo</span></p></div><div className={s.heroPanel}><span className={s.orbit} /><p>Depilação a laser</p><strong>4 perguntas</strong><ul><li>Regiões que incomodam</li><li>Sua rotina de depilação</li><li>Condição e horários</li></ul><small>Escolha uma ou mais áreas que gostaria de tratar.</small></div></section>
    <section className={s.quizSection} id="quiz-laser"><div className={s.quizIntro}><p className={s.eyebrow}>Laser Day • depilação a laser</p><h2>Comece pelas regiões que mais fazem diferença para você.</h2><p>Em menos de um minuto, você informa as áreas de interesse e consulta a condição da próxima edição.</p></div><div className={s.quizCard} aria-live="polite"><div className={s.quizTop}><span>{step === 0 ? "Pronto para começar" : step <= 4 ? `Pergunta ${step} de 4` : step === 5 ? "Seus dados" : step === 6 ? "Sua condição" : "Pré-reserva"}</span><b>{progress}%</b></div><div className={s.progress}><span style={{ width: `${progress}%` }} /></div>
      {step === 0 && <div className={s.quizBody}><p className={s.quizKicker}>Laser Day • PS Estética</p><h3>Em quais regiões os pelos mais incomodam você?</h3><p className={s.quizText}>Responda algumas perguntas rápidas e descubra a condição especial da próxima edição para as áreas que gostaria de tratar.</p><button className={s.primary} onClick={start}>Começar <span>›</span></button><p className={s.cardTrust}><b>Leva menos de 1 minuto</b><br /><span>São Bernardo do Campo</span></p></div>}
      {current && <div className={s.quizBody}><p className={s.quizKicker}>Pergunta {step} de 4</p><h3>{current.title}</h3><div className={s.options}>{current.options.map((option) => <button key={option.label} className={`${answers[current.key] === option.label ? s.selected : ""} ${current.key === "concern" ? s.regionOption : ""}`} data-tone={current.key === "concern" ? regionTone[option.label] : undefined} onClick={() => choose(option.label)}>{current.key === "concern" && <span className={s.regionBadge} aria-hidden="true">{option.label === "Quero tratar mais de uma região" ? "+" : option.label.slice(0, 2)}</span>}<span><b>{option.label}</b></span><i>›</i></button>)}</div>{current.key === "impact" && answers.impact !== "" && answers.impact !== "Não, quero focar apenas nessa região" && <div className={s.regionPicker}><p className={s.quizKicker}>Quais outras regiões você gostaria de tratar?</p><div>{availableRegions.filter((region) => region !== answers.concern).map((region) => <button type="button" key={region} className={otherRegions.includes(region) ? s.selectedRegion : ""} onClick={() => toggleRegion(region)}><span>{otherRegions.includes(region) ? "✓" : "+"}</span>{region}</button>)}</div><button type="button" className={s.primary} disabled={otherRegions.length === 0} onClick={() => setStep(3)}>Continuar <span>›</span></button></div>}{step > 1 && <button className={s.back} onClick={() => setStep((step - 1) as Step)}>Voltar</button>}</div>}
      {step === 5 && <form className={`${s.quizBody} ${s.contactForm}`} onSubmit={submitContact}><p className={s.quizKicker}>Pronto! Recebemos suas respostas.</p><h3>Deixe seus dados para ver sua condição.</h3><p className={s.quizText}>Você selecionou <b>{regionsLabel}</b>. Agora poderá consultar a próxima edição do Laser Day.</p><label>Nome<input required minLength={2} value={name} onChange={(e) => { setName(e.target.value); setLead(null); }} autoComplete="name" /></label><label>WhatsApp<input required value={phone} onChange={(e) => { setPhone(formatBrazilianWhatsapp(e.target.value)); setLead(null); setNotice(""); }} inputMode="numeric" maxLength={15} minLength={15} pattern="\([1-9]\d\) 9\d{4}-\d{4}" title={INVALID_WHATSAPP_MESSAGE} placeholder="(11) 90000-0000" /><small>Informe um celular com DDD e todos os 9 dígitos.</small></label><label>E-mail<input required type="email" value={email} onChange={(e) => { setEmail(e.target.value); setLead(null); }} autoComplete="email" /></label><button className={s.primary} disabled={loading}>{loading ? "Consultando…" : "Ver minha condição"} <span>›</span></button>{notice && <p className={s.notice}>{notice}</p>}<button className={s.back} type="button" onClick={() => setStep(4)}>Voltar</button><small className={s.privacy}>Seus dados serão usados apenas no atendimento da PS Estética.</small></form>}
      {step === 6 && <div className={s.quizBody}><p className={s.resultLabel}>Pronto! Recebemos suas respostas.</p><h3>Você selecionou {regionsLabel}.</h3><p className={s.resultText}>Agora você pode conferir a condição do próximo <b>Laser Day da PS Estética</b> para depilação a laser.</p><div className={s.answerSummary}><span>Sua seleção</span><strong>{regionsLabel}</strong></div><div className={s.scheduleHead}><p className={s.quizKicker}>Próximo Laser Day</p><h4>Veja a condição e consulte os horários</h4></div>{loading && <p className={s.notice}>Consultando a agenda…</p>}{!loading && slots.length > 0 && <div className={s.slots}>{slots.map((slot) => <button key={slot.slot_id} onClick={() => setSelected(slot)} className={selected?.slot_id === slot.slot_id ? s.selectedSlot : ""}><span><small>Disponível</small>{formatSlot(slot.starts_at)}</span><i>›</i></button>)}</div>}{!loading && slots.length === 0 && <div className={s.empty}><b>A próxima data será divulgada em breve.</b><p>Consulte a condição, o valor e os horários diretamente com a equipe.</p><a href={whatsapp} target="_blank" rel="noreferrer">Ver minha condição</a></div>}{selected && <form className={s.reserveBox} onSubmit={reserve}><div><small>Horário escolhido</small><b>{formatSlot(selected.starts_at)}</b></div><p className={s.reserveEmail}>A confirmação será enviada para <b>{email}</b></p><button className={s.primary} disabled={loading}>{loading ? "Criando pré-reserva…" : "Quero garantir meu horário"} <span>›</span></button></form>}<small className={s.privacy}>A possibilidade de realização e o protocolo adequado são avaliados individualmente.</small>{notice && <p className={s.notice}>{notice}</p>}</div>}
      {step === 7 && booking && <div className={s.quizBody}><p className={s.resultLabel}>Horário separado para você</p><h3>{formatSlot(booking.starts_at)}</h3>{paid ? <div className={s.paid}><b>Pagamento confirmado</b><p>Seu horário está confirmado.</p><a href={whatsapp} target="_blank" rel="noreferrer">Falar com a equipe</a></div> : <><p className={s.resultText}>Conclua o sinal de R$ {(booking.deposit_cents / 100).toFixed(2).replace(".", ",")} para confirmar. Se o prazo expirar, o horário volta a ficar disponível.</p>{pix?.qr_code_base64 && <Image className={s.qr} src={`data:image/png;base64,${pix.qr_code_base64}`} width={220} height={220} alt="QR Code Pix" />}{pix?.pix_copy_paste && <button className={s.primary} type="button" onClick={copyPix}>Copiar código Pix</button>}{pix?.ticket_url && <a className={s.paymentLink} href={pix.ticket_url} target="_blank" rel="noreferrer">Abrir pagamento</a>}</>}{notice && <p className={s.notice}>{notice}</p>}</div>}
    </div></section>
    <section className={s.benefits}><div className={s.sectionIntro}><p className={s.eyebrow}>Condição especial • Laser Day</p><h2>Menos preocupação com os pelos. Mais praticidade na sua rotina.</h2><p>No próximo <b>Laser Day da PS Estética</b>, você poderá realizar depilação a laser nas regiões participantes com uma condição especial para o evento.</p></div><div className={s.benefitGrid}><article><span>01</span><h3>Regiões escolhidas</h3><p>Monte sua seleção de acordo com as áreas que mais incomodam.</p></article><article><span>02</span><h3>Condição Laser Day</h3><p>Consulte o valor especial válido para a próxima edição.</p></article><article><span>03</span><h3>Combinações</h3><p>A equipe informa os combos disponíveis para mais de uma região.</p></article><article><span>04</span><h3>Horários</h3><p>Consulte a disponibilidade real da agenda para o evento.</p></article><article><span>05</span><h3>Orientação</h3><p>Tire suas dúvidas antes de confirmar o pré-agendamento.</p></article></div><a className={s.primary} href={whatsapp} target="_blank" rel="noreferrer">Quero garantir meu horário <span>›</span></a><p className={s.disclaimer}>Você será direcionada para o WhatsApp da PS Estética.</p></section>
    <section className={s.how}><div className={s.sectionIntro}><p className={s.eyebrow}>Por que fazer depilação a laser?</p><h2>Redução progressiva dos pelos nas regiões que fazem diferença para você.</h2></div><ol><li><span>1</span><div><h3>Mais praticidade</h3><p>Uma alternativa para quem está cansada de organizar a rotina em torno de lâmina, cera ou métodos temporários.</p></div></li><li><span>2</span><div><h3>Escolha suas regiões</h3><p>Axilas, virilha, pernas, rosto e outras áreas participantes da edição.</p></div></li><li><span>3</span><div><h3>Protocolo individual</h3><p>A possibilidade de realização e o número de sessões são avaliados individualmente.</p></div></li></ol></section>
    <section className={s.fit}><div><p className={s.eyebrow}>Dúvidas rápidas</p><h2>Antes de reservar, saiba como funciona.</h2><p>Você pode conversar com a equipe e esclarecer tudo pelo WhatsApp.</p></div><div className={s.fitCards}><article><span>01</span><h3>Posso fazer mais de uma região?</h3><p>Sim, desde que façam parte das opções do Laser Day. Consulte combinações e condições com a equipe.</p></article><article><span>02</span><h3>Nunca fiz depilação a laser. Posso participar?</h3><p>A equipe orienta você sobre o procedimento e avalia seu caso antes da realização.</p></article><article><span>03</span><h3>Quantas sessões vou precisar?</h3><p>Isso varia conforme a região e as características individuais. A equipe orientará o protocolo adequado.</p></article><article><span>04</span><h3>Posso falar com alguém antes?</h3><p>Sim. Você pode tirar suas dúvidas pelo WhatsApp antes de reservar.</p></article></div></section>
    <section className={s.confidence}><p className={s.eyebrow}>Laser Day • próxima edição</p><h2>Quais regiões você gostaria de parar de depilar com tanta frequência?</h2><p>Você já selecionou as áreas que mais incomodam. Agora consulte a <b>condição do próximo Laser Day</b> e os horários disponíveis.</p><div><span>Depilação a laser</span><span>São Bernardo do Campo/SP</span><span>Agenda limitada</span></div><a className={s.primary} href={whatsapp} target="_blank" rel="noreferrer">Quero consultar disponibilidade <span>›</span></a></section>
    <footer className={s.footer}><Image src="/ps-estetica-logo-oficial.png" width={246} height={80} alt="PS Estética" /><p>São Bernardo do Campo • ABC Paulista</p><small>O conteúdo desta página é informativo. A indicação de qualquer procedimento depende de avaliação individual.</small></footer>
  </main>;
}
